import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: [
    {
      path: "../../public/fonts/Satoshi-Regular.woff",
      weight: "400",
    },
    {
      path: "../../public/fonts/Satoshi-Medium.woff",
      weight: "500",
    },
    {
      path: "../../public/fonts/Satoshi-Bold.woff",
      weight: "700",
    },
    {
      path: "../../public/fonts/Satoshi-Black.woff",
      weight: "900",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
        <body className={`${satoshi.variable} antialiased`}>{children}</body>
      
    </html>
  );
}
